server:
  port: 8080
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: in28minutes
      password: dummy
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: debug

weather:
  id: "someID"
  url: "someURL"
  absoluteFilePath: "someFile"
  fixedDelayInMilli: 3600000

jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
