server:
  port: 8080
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: info
weather:
  id: "someID"
  url: "someURL"
  absoluteFilePath: "someFile"
  fixedDelayInMilli: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus